apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agro-app
  namespace: agro-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: agro-app
  namespaceSelector:
    matchNames:
      - agro-app
  endpoints:
    - port: web
      path: /metrics
      interval: 15s
