replicaCount: 3

image:
  repository: YOUR_DOCKERHUB_USER/agro-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  name: web

metrics:
  enabled: true
  path: /metrics

postgresql:
  enabled: true
  auth:
    username: agro
    password: agro-pass-123
    database: agrodb
  primary:
    persistence:
      enabled: true
      size: 1Gi

externalDatabase:
  enabled: false
  url: ""
