apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agro-app.fullname" . }}
  labels:
    release: kube-prometheus-stack
    app: agro-app
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: agro-app
  endpoints:
    - port: web
      path: /metrics
      interval: 15s
